trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scotch-score

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)/scotch-score'

  - task: Npm@1
    displayName: 'npm run test'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/scotch-score'
      customCommand: 'run test:ci'

  - task: Npm@1
    displayName: 'npm run build'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/scotch-score'
      customCommand: 'run build'

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/scotch-score/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/scotch-score.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    name: 'PublishBuildArtifacts'
    displayName: 'Publish build artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'scotch-score'
      publishLocation: 'Container'
