trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scotch-score

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(Build.SourcesDirectory)/ScotchScore/scotch-score'
  displayName: 'npm install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/ScotchScore/scotch-score'
    customCommand: 'run test:ci'
  displayName: 'npm run test:ci'
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/ScotchScore/scotch-score'
    customCommand: 'run build'
  displayName: 'npm run build'
